version: '3'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # MySQLの設定ファイル
      - ./build/db_prod/my.cnf:/etc/mysql/conf.d/my.cnf
      # DBのデータを永続化する
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    # environmentはenv_fileの前に読み込まれるのでenv_fileで直接環境変数を設定する
    env_file:
      - .env.prod

  nginx:
    image: steveltn/https-portal:1.7.3
    restart: always
    links:
      - app:app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginxの設定ファイルを上書きする
      - ./build/nginx/conf/localhost.ssl.conf.erb:/var/lib/nginx-conf/localhost.conf.erb:ro
      # unix domain socket通信するのでRailsとディレクトリを共有する
      - tmp-data:/docker_rails/tmp
    environment:
      STAGE: local
      DOMAINS: 'localhost => https://localhost'

  app:
    build:
      context: ./
      dockerfile: ./build/rails/Dockerfile
    command: bash -c "bundle exec rake assets:precompile && bundle exec pumactl start"
    volumes:
      - .:/myapp
      # unix domain socket通信するのでNginxとディレクトリを共有する
      - tmp-data:/myapp/tmp
      # logを永続化
      - log-data:/myapp/log
    # dockerizeを用いてdbが起動し終わるまで待つ
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://db:3306
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.prod

volumes:
  db-data:
  tmp-data:
  log-data:
